#!/usr/bin/env bash

BASE_IMG_NAME="devenv"
NO_NEW_IMG=false

# Order of parameters :
#   1. flag to use base img for the container
#   2. name
#   3. path to project (to share folder)
usage() {
    echo "Usage: devenv [-n for no new image] <container name> [project path]"
}

# Parse argument -n
while getopts "n" opt; do 
    case ${opt} in 
        n) NO_NEW_IMG=true;;
    esac
done
shift $(($OPTIND - 1))

NAME=$1
PROJECT_PATH=$(realpath ${2:-$(pwd)})

if [ -z $NAME ]; then
    usage
    exit 1
fi

# Create base image
if ! podman image exists $BASE_IMG_NAME; then
    podman build -f ~/BaseEnvContainerfile -t devenv .
fi

# Create other image if needed
if [ $NO_NEW_IMG = true ]; then
    IMG_NAME=$BASE_IMG_NAME
else 
    IMG_NAME=$NAME
    podman build -f $PROJECT_PATH/EnvContainerfile -t $NAME $PROJECT_PATH
fi

# Create container with correct image, volumes and namespace
podman create -t --name $NAME \
    --userns=keep-id \
    -v $HOME/.config/nvim:/home/jdumas/.config/nvim \
    -v $HOME/.local/dev/nvim-container-share:/home/jdumas/.local/share/nvim \
    -v $PROJECT_PATH:/home/jdumas/src \
    -h $NAME $IMG_NAME
