#!/usr/bin/env bash

NO_NEW_IMG=false
# Order of parameters :
#   1. flag to use base img for the container
#   2. name
#   3. path to project (to share folder)
usage() {
    echo "Usage: devenv [-n for no new image] <container name> [project path]"
}
while getopts "n" opt; do 
    case ${opt} in 
        n) NO_NEW_IMG=true;;
    esac
done
shift $(($OPTIND - 1))

NAME=$1
PROJECT_PATH=$(realpath ${2:-$(pwd)})

if [ -z $NAME ]; then
    usage
    exit 1
fi
